name: Test hw01_hello_otus

on:
  push:
    branches: [ hw01_hello_otus ]
  pull_request:
    branches: [ hw01_hello_otus ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: cd hw01_hello_otus && pwd && ls -la && ./test.sh
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.18.0'
    - run: cd hw01_hello_otus && go test -v -count=1 -race -timeout=1m .
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3.1.0
      with:
        working-directory: hw01_hello_otus
